
name: CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.3.2
      - uses: cachix/install-nix-action@v10
      - uses: cachix/cachix-action@v6
        with:
          name: layus
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          # Only needed for private caches
          #authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-build
      - run: nix-shell --run "./result/bin/site build"
  
      - name: Release to mamster
        if: success()
        uses: ad-m/github-push-action@v0.6.0
        with:
          # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          # Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})
          #repository: ${GITHUB_REPOSITORY} 
          # Destination branch to push changes
          #branch: # optional, default is master
          # Determines if force push is used
          force: false
          # Determines if --tags is used
          tags: false
          # Directory to change to before pushing.
          directory: _site
